trigger:
    batch: true
    branches:
        include:
        - main
        - develop
    paths:
        include: 
        - "./Assesment/*"

pool:
  name: 'Azure Pipelines'


variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')] #not used
  isDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')] #not used
  test: ""

stages:
- template: templates/stage_level_templates/test_build_stage_template.yml # stage template to test, build and push
  parameters:
    projectFolder: Dawood/Assesment/HackerRank.Monitoring.Api/HackerRank.Monitoring.Api.csproj #${{variables.projectFolder}}
    buildOutputFolder: $(BUILDOUTPUTFOLDER) #${{variables.buildOutputFolder}}
    sourceFolder: $(SOURCEFOLDER) #${{variables.sourceFolder}}
    vmImageName: $(VMIMAGE)
    

- template: templates/stage_level_templates/az_deployment_stage_template.yml # stage template for azure resource deployment to Develop
  parameters:
    vmImageName : $(VMIMAGE) #${{variables.vmImage}}
    azureSubscription : "YousufAli& Harsha"
    resourceGroup : "Assessment_Dawood"
    bicepFilePath : "Dawood/Assesment/infrastructure/main.bicep"
    parameterFilePath : "Dawood/Assesment/infrastructure/main.parameters-dev.json"
    jobName : "resourcedeployment"
    jobDescription : "deployemnt of resources"
    scriptType : "bash"
    environment: 'dev'
    deploy: true

- template: templates/stage_level_templates/app_deployment_stage_template.yml #stage template for application deployment
  parameters:
    #serviceConnection: "InternsAssignment"
    serviceConnection: "DawoodAssesment"
    subscriptionId: 'dev'
    environment: 'dev'
    appType: 'webApp'
